export enum BadgeType {
  FIRST_TASK = 'FIRST_TASK',
  STREAK_7_DAYS = 'STREAK_7_DAYS',
  STREAK_30_DAYS = 'STREAK_30_DAYS',
  STREAK_100_DAYS = 'STREAK_100_DAYS',
  HEALTH_CHAMPION = 'HEALTH_CHAMPION',
}
